# NumPy 

<h2 style="color: green;">Let's dive into some basics</h2>


## NumPy (Numerical Python) is a Python library used for:
- Fast numerical computations  
- Handling large arrays and matrices  
- Performing linear algebra, Fourier transforms, random number generation, and more.

### Why Use NumPy?
#### Compared to plain Python lists:
- Much faster (written in C under the hood)
- Supports multi-dimensional arrays
- Has tons of built-in math functions
- Works seamlessly with data science tools like Pandas, Matplotlib, and SciPy

### Python List

In [2]:
my_list = [1, 2, 3]

In [4]:
my_list

[1, 2, 3]

### NumPy Array

In [9]:
import numpy as np

In [8]:
arr = np.array(my_list)

In [10]:
arr

array([1, 2, 3])

In [12]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [14]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [20]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [24]:
np.zeros(3)

array([0., 0., 0.])

In [30]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [32]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [36]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

### Identity Matrix

In [41]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Arrays of Random numbers

### rand  
##### Uniform distribution in the range [0, 1).

In [14]:
np.random.rand(5)

array([0.89615289, 0.05649541, 0.69856676, 0.14394331, 0.78851178])

In [48]:
np.random.rand(5,5)

array([[0.21907398, 0.9632315 , 0.87679853, 0.76874924, 0.98512706],
       [0.85601249, 0.74320462, 0.93683891, 0.28575991, 0.71844106],
       [0.95399518, 0.40019483, 0.16400341, 0.12572391, 0.19187019],
       [0.92303795, 0.81489646, 0.41409132, 0.39579339, 0.78187549],
       [0.72574831, 0.76451963, 0.27440339, 0.331185  , 0.06095535]])

### randn  
##### Standard normal distribution (also called Gaussian distribution), i.e., mean = 0, standard deviation = 1 ==>(numbers which are more likely to be near 0, and values farther from 0 are less likely.)

In [20]:
np.random.randn(4)

array([0.06140524, 0.36815939, 1.17240569, 0.9625203 ])

In [52]:
np.random.randn(4,3)

array([[-0.1900765 ,  1.10929828,  1.05957783],
       [-0.47633272, -0.31179721,  1.95368932],
       [ 1.24943635, -0.03177245,  0.38637851],
       [-2.08119596, -0.15588175,  1.42327761]])

In [27]:
np.random.randint(1,100) # Any integer between 1 to 99

15

In [29]:
np.random.randint(1,100,5) ## 5 integer between 1 to 99

array([40, 65, 59, 63, 80])

In [10]:
arr = np.arange(25)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [14]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [16]:
arr.reshape(5,3)

ValueError: cannot reshape array of size 25 into shape (5,3)

### Max and Min 

In [18]:
ranArr = np.random.randint(40,50,10)

In [20]:
ranArr

array([44, 42, 47, 45, 40, 44, 49, 40, 45, 44])

In [22]:
ranArr.max()

49

In [24]:
ranArr.min()

40

### Index of Max and Min

In [26]:
ranArr.argmax()

6

In [28]:
ranArr.argmin()

4

In [30]:
arr = np.random.randint(1,100,25)

In [32]:
arr.shape

(25,)

In [48]:
arr = arr.reshape(5,5)

In [50]:
arr

array([[56, 26, 16, 71, 32],
       [52, 80, 92, 98, 95],
       [28, 91, 75, 60, 91],
       [77,  7, 29, 59, 27],
       [59, 41, 24, 13,  8]])

In [52]:
arr.shape

(5, 5)

### Slicing

In [37]:
import numpy as np

In [39]:
arr = np.arange(0,11)

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr[8]

8

In [45]:
arr[1:5]

array([1, 2, 3, 4])

In [47]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [51]:
arr[0:5] = 100

In [53]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [55]:
arr = np.arange(0,11)

In [113]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [117]:
slice_of_arr = arr[0:6]

In [119]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [121]:
slice_of_arr[ ] = 99

In [123]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [125]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [127]:
arr_copy = arr.copy()

In [129]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [131]:
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [133]:
arr_copy[:] = 200

In [135]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [137]:
arr_copy

array([200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200])

### 2D Array

In [142]:
arr_2d = np.array([[5,10,15], [20,25,30], [35,40,45]])

In [144]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [146]:
arr_2d[1][2]

30

In [148]:
arr_2d[1,2]

30

In [150]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [152]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [156]:
arr = np.arange(1,11)

In [158]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [160]:
bool_arr = arr > 5

In [162]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [164]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [166]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [168]:
arr[arr<3]

array([1, 2])

In [170]:
arr_2d = np.arange(50).reshape(5,10)

In [172]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [176]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])

In [10]:
arr = np.arange(0,11)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [18]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [19]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [20]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [22]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [24]:
arr/arr

C:\Users\user\AppData\Local\Temp\ipykernel_3304\1862401812.py:1: RuntimeWarning: invalid value encountered in divide
  arr/arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [30]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [33]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [35]:
np.log(arr)

C:\Users\user\AppData\Local\Temp\ipykernel_3304\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])